### ISSUE TITLE
Connect to mySQL from Python

### ISSUE THREAD

**Issue by adcar** [adcar/vermontaholic#5]
Get MySQL access and connect to it from Python. Create a new database in MySQL and decide how the schema should look

**Comment by ghost** [comment]
Schema made

CREATE TABLE `users` (
	`username` VARCHAR(30) CHARACTER SET ascii COLLATE ascii_bin DEFAULT 'default',
	`passwordhash` VARCHAR(64) DEFAULT 'password'
);

CREATE TABLE `main` (
	`username` VARCHAR(30),
	`location` VARCHAR(64),
	`date` DATETIME,
	`picture` INT(16),
	`comment` VARCHAR(512)
);

**Comment by adcar** [comment]
**List of all VT towns**

Schema:
```CREATE TABLE towns ( name VARCHAR(64) );```

Inserts:
https://pastebin.com/2YRvzfPr

**Comment by ghost** [comment]
Town table added and towns inserted

**Comment by adcar** [comment]
@silas730 the towns table will be useful for you when building the `GET /towns/<user>` endpoint as described in #4
